module

-- This file is generated by scripts/gen_traits.py. Do not edit.
public import PiBaseLean.Spaces.S4.Lemmas
public import PiBaseLean.Properties.P176.Bundled
public import PiBaseLean.Properties.P185.Bundled
public import PiBaseLean.Properties.P204.Bundled
public import PiBaseLean.Properties.P205.Bundled
public import PiBaseLean.Theorems.T430.Theorem
public import PiBaseLean.Theorems.T448.Theorem
public import PiBaseLean.Theorems.T558.Theorem
public import PiBaseLean.Theorems.T635.Theorem

@[expose] public section

namespace PiBase.Formal

theorem S4_P176_not : ¬ P176 PiBase.S4 := by
  intro h
  exact S4_P175_not (T430 PiBase.S4 inferInstance h)

register_certificate S000004 P000176 false
  proof PiBase.Formal.S4_P176_not
  provenance derived
  assumptions []

theorem S4_P185 : P185 PiBase.S4 :=
  T448 PiBase.S4 inferInstance S4_P129

register_certificate S000004 P000185 true
  proof PiBase.Formal.S4_P185
  provenance derived
  assumptions []

theorem S4_P204_not : ¬ P204 PiBase.S4 := by
  intro h
  exact S4_P175_not (T558 PiBase.S4 inferInstance h)

register_certificate S000004 P000204 false
  proof PiBase.Formal.S4_P204_not
  provenance derived
  assumptions []

theorem S4_P205_not : ¬ P205 PiBase.S4 := by
  intro h
  exact S4_P204_not (T635 PiBase.S4 inferInstance h)

register_certificate S000004 P000205 false
  proof PiBase.Formal.S4_P205_not
  provenance derived
  assumptions []

end PiBase.Formal
