module

/-
  DO NOT EDIT. Generated by `scripts/gen_statement_check.py` from `data/pibase.json`.
  Regenerate with `python3 scripts/gen_statement_check.py`.
-/

public import PiBaseLean.Bundled.Basic
public import PiBaseLean.Properties.P1.Bundled
public import PiBaseLean.Properties.P2.Bundled
public import PiBaseLean.Properties.P3.Bundled
public import PiBaseLean.Properties.P4.Bundled
public import PiBaseLean.Properties.P5.Bundled
public import PiBaseLean.Properties.P6.Bundled
public import PiBaseLean.Properties.P7.Bundled
public import PiBaseLean.Properties.P8.Bundled
public import PiBaseLean.Properties.P9.Bundled
public import PiBaseLean.Properties.P11.Bundled
public import PiBaseLean.Properties.P12.Bundled
public import PiBaseLean.Properties.P13.Bundled
public import PiBaseLean.Properties.P14.Bundled
public import PiBaseLean.Properties.P15.Bundled
public import PiBaseLean.Properties.P16.Bundled
public import PiBaseLean.Properties.P17.Bundled
public import PiBaseLean.Properties.P18.Bundled
public import PiBaseLean.Properties.P19.Bundled
public import PiBaseLean.Properties.P20.Bundled
public import PiBaseLean.Properties.P21.Bundled
public import PiBaseLean.Properties.P22.Bundled
public import PiBaseLean.Properties.P23.Bundled
public import PiBaseLean.Properties.P24.Bundled
public import PiBaseLean.Properties.P25.Bundled
public import PiBaseLean.Properties.P26.Bundled
public import PiBaseLean.Properties.P27.Bundled
public import PiBaseLean.Properties.P28.Bundled
public import PiBaseLean.Properties.P29.Bundled
public import PiBaseLean.Properties.P30.Bundled
public import PiBaseLean.Properties.P31.Bundled
public import PiBaseLean.Properties.P32.Bundled
public import PiBaseLean.Properties.P34.Bundled
public import PiBaseLean.Properties.P35.Bundled
public import PiBaseLean.Properties.P36.Bundled
public import PiBaseLean.Properties.P37.Bundled
public import PiBaseLean.Properties.P38.Bundled
public import PiBaseLean.Properties.P39.Bundled
public import PiBaseLean.Properties.P40.Bundled
public import PiBaseLean.Properties.P41.Bundled
public import PiBaseLean.Properties.P42.Bundled
public import PiBaseLean.Properties.P43.Bundled
public import PiBaseLean.Properties.P44.Bundled
public import PiBaseLean.Properties.P45.Bundled
public import PiBaseLean.Properties.P46.Bundled
public import PiBaseLean.Properties.P47.Bundled
public import PiBaseLean.Properties.P48.Bundled
public import PiBaseLean.Properties.P49.Bundled
public import PiBaseLean.Properties.P51.Bundled
public import PiBaseLean.Properties.P52.Bundled
public import PiBaseLean.Properties.P53.Bundled
public import PiBaseLean.Properties.P55.Bundled
public import PiBaseLean.Properties.P57.Bundled
public import PiBaseLean.Properties.P58.Bundled
public import PiBaseLean.Properties.P59.Bundled
public import PiBaseLean.Properties.P60.Bundled
public import PiBaseLean.Properties.P62.Bundled
public import PiBaseLean.Properties.P63.Bundled
public import PiBaseLean.Properties.P64.Bundled
public import PiBaseLean.Properties.P65.Bundled
public import PiBaseLean.Properties.P66.Bundled
public import PiBaseLean.Properties.P67.Bundled
public import PiBaseLean.Properties.P68.Bundled
public import PiBaseLean.Properties.P73.Bundled
public import PiBaseLean.Properties.P74.Bundled
public import PiBaseLean.Properties.P75.Bundled
public import PiBaseLean.Properties.P77.Bundled
public import PiBaseLean.Properties.P78.Bundled
public import PiBaseLean.Properties.P79.Bundled
public import PiBaseLean.Properties.P80.Bundled
public import PiBaseLean.Properties.P83.Bundled
public import PiBaseLean.Properties.P84.Bundled
public import PiBaseLean.Properties.P85.Bundled
public import PiBaseLean.Properties.P86.Bundled
public import PiBaseLean.Properties.P87.Bundled
public import PiBaseLean.Properties.P88.Bundled
public import PiBaseLean.Properties.P89.Bundled
public import PiBaseLean.Properties.P90.Bundled
public import PiBaseLean.Properties.P92.Bundled
public import PiBaseLean.Properties.P93.Bundled
public import PiBaseLean.Properties.P94.Bundled
public import PiBaseLean.Properties.P95.Bundled
public import PiBaseLean.Properties.P96.Bundled
public import PiBaseLean.Properties.P98.Bundled
public import PiBaseLean.Properties.P100.Bundled
public import PiBaseLean.Properties.P102.Bundled
public import PiBaseLean.Properties.P103.Bundled
public import PiBaseLean.Properties.P104.Bundled
public import PiBaseLean.Properties.P105.Bundled
public import PiBaseLean.Properties.P107.Bundled
public import PiBaseLean.Properties.P108.Bundled
public import PiBaseLean.Properties.P110.Bundled
public import PiBaseLean.Properties.P112.Bundled
public import PiBaseLean.Properties.P113.Bundled
public import PiBaseLean.Properties.P114.Bundled
public import PiBaseLean.Properties.P116.Bundled
public import PiBaseLean.Properties.P117.Bundled
public import PiBaseLean.Properties.P118.Bundled
public import PiBaseLean.Properties.P119.Bundled
public import PiBaseLean.Properties.P120.Bundled
public import PiBaseLean.Properties.P121.Bundled
public import PiBaseLean.Properties.P122.Bundled
public import PiBaseLean.Properties.P123.Bundled
public import PiBaseLean.Properties.P124.Bundled
public import PiBaseLean.Properties.P125.Bundled
public import PiBaseLean.Properties.P126.Bundled
public import PiBaseLean.Properties.P127.Bundled
public import PiBaseLean.Properties.P129.Bundled
public import PiBaseLean.Properties.P130.Bundled
public import PiBaseLean.Properties.P131.Bundled
public import PiBaseLean.Properties.P132.Bundled
public import PiBaseLean.Properties.P133.Bundled
public import PiBaseLean.Properties.P134.Bundled
public import PiBaseLean.Properties.P135.Bundled
public import PiBaseLean.Properties.P136.Bundled
public import PiBaseLean.Properties.P137.Bundled
public import PiBaseLean.Properties.P139.Bundled
public import PiBaseLean.Properties.P140.Bundled
public import PiBaseLean.Properties.P141.Bundled
public import PiBaseLean.Properties.P142.Bundled
public import PiBaseLean.Properties.P145.Bundled
public import PiBaseLean.Properties.P147.Bundled
public import PiBaseLean.Properties.P149.Bundled
public import PiBaseLean.Properties.P150.Bundled
public import PiBaseLean.Properties.P153.Bundled
public import PiBaseLean.Properties.P154.Bundled
public import PiBaseLean.Properties.P155.Bundled
public import PiBaseLean.Properties.P162.Bundled
public import PiBaseLean.Properties.P163.Bundled
public import PiBaseLean.Properties.P165.Bundled
public import PiBaseLean.Properties.P166.Bundled
public import PiBaseLean.Properties.P168.Bundled
public import PiBaseLean.Properties.P169.Bundled
public import PiBaseLean.Properties.P170.Bundled
public import PiBaseLean.Properties.P172.Bundled
public import PiBaseLean.Properties.P173.Bundled
public import PiBaseLean.Properties.P175.Bundled
public import PiBaseLean.Properties.P176.Bundled
public import PiBaseLean.Properties.P177.Bundled
public import PiBaseLean.Properties.P178.Bundled
public import PiBaseLean.Properties.P179.Bundled
public import PiBaseLean.Properties.P180.Bundled
public import PiBaseLean.Properties.P181.Bundled
public import PiBaseLean.Properties.P182.Bundled
public import PiBaseLean.Properties.P183.Bundled
public import PiBaseLean.Properties.P185.Bundled
public import PiBaseLean.Properties.P188.Bundled
public import PiBaseLean.Properties.P189.Bundled
public import PiBaseLean.Properties.P191.Bundled
public import PiBaseLean.Properties.P192.Bundled
public import PiBaseLean.Properties.P195.Bundled
public import PiBaseLean.Properties.P196.Bundled
public import PiBaseLean.Properties.P197.Bundled
public import PiBaseLean.Properties.P198.Bundled
public import PiBaseLean.Properties.P199.Bundled
public import PiBaseLean.Properties.P200.Bundled
public import PiBaseLean.Properties.P201.Bundled
public import PiBaseLean.Properties.P203.Bundled
public import PiBaseLean.Properties.P204.Bundled
public import PiBaseLean.Properties.P205.Bundled
public import PiBaseLean.Properties.P208.Bundled
public import PiBaseLean.Properties.P210.Bundled
public import PiBaseLean.Properties.P211.Bundled
public import PiBaseLean.Properties.P212.Bundled
public import PiBaseLean.Properties.P213.Bundled
public import PiBaseLean.Properties.P214.Bundled
public import PiBaseLean.Properties.P215.Bundled
public import PiBaseLean.Properties.P216.Bundled
public import PiBaseLean.Properties.P218.Bundled
public import PiBaseLean.Properties.P219.Bundled
public import PiBaseLean.Properties.P220.Bundled
public import PiBaseLean.Properties.P222.Bundled
public import PiBaseLean.Properties.P227.Bundled
public import PiBaseLean.Properties.P228.Bundled
public import PiBaseLean.Properties.P230.Bundled
public import PiBaseLean.Properties.P231.Bundled
public import PiBaseLean.Properties.P233.Bundled
public import PiBaseLean.Properties.P234.Bundled
public import PiBaseLean.Theorems.T1.Theorem
public import PiBaseLean.Theorems.T2.Theorem
public import PiBaseLean.Theorems.T3.Theorem
public import PiBaseLean.Theorems.T4.Theorem
public import PiBaseLean.Theorems.T7.Theorem
public import PiBaseLean.Theorems.T8.Theorem
public import PiBaseLean.Theorems.T9.Theorem
public import PiBaseLean.Theorems.T11.Theorem
public import PiBaseLean.Theorems.T13.Theorem
public import PiBaseLean.Theorems.T14.Theorem
public import PiBaseLean.Theorems.T21.Theorem
public import PiBaseLean.Theorems.T22.Theorem
public import PiBaseLean.Theorems.T25.Theorem
public import PiBaseLean.Theorems.T27.Theorem
public import PiBaseLean.Theorems.T31.Theorem
public import PiBaseLean.Theorems.T32.Theorem
public import PiBaseLean.Theorems.T33.Theorem
public import PiBaseLean.Theorems.T34.Theorem
public import PiBaseLean.Theorems.T35.Theorem
public import PiBaseLean.Theorems.T36.Theorem
public import PiBaseLean.Theorems.T37.Theorem
public import PiBaseLean.Theorems.T38.Theorem
public import PiBaseLean.Theorems.T39.Theorem
public import PiBaseLean.Theorems.T40.Theorem
public import PiBaseLean.Theorems.T41.Theorem
public import PiBaseLean.Theorems.T42.Theorem
public import PiBaseLean.Theorems.T43.Theorem
public import PiBaseLean.Theorems.T45.Theorem
public import PiBaseLean.Theorems.T46.Theorem
public import PiBaseLean.Theorems.T47.Theorem
public import PiBaseLean.Theorems.T48.Theorem
public import PiBaseLean.Theorems.T49.Theorem
public import PiBaseLean.Theorems.T51.Theorem
public import PiBaseLean.Theorems.T52.Theorem
public import PiBaseLean.Theorems.T55.Theorem
public import PiBaseLean.Theorems.T58.Theorem
public import PiBaseLean.Theorems.T59.Theorem
public import PiBaseLean.Theorems.T60.Theorem
public import PiBaseLean.Theorems.T61.Theorem
public import PiBaseLean.Theorems.T63.Theorem
public import PiBaseLean.Theorems.T64.Theorem
public import PiBaseLean.Theorems.T66.Theorem
public import PiBaseLean.Theorems.T67.Theorem
public import PiBaseLean.Theorems.T68.Theorem
public import PiBaseLean.Theorems.T74.Theorem
public import PiBaseLean.Theorems.T76.Theorem
public import PiBaseLean.Theorems.T77.Theorem
public import PiBaseLean.Theorems.T78.Theorem
public import PiBaseLean.Theorems.T81.Theorem
public import PiBaseLean.Theorems.T84.Theorem
public import PiBaseLean.Theorems.T85.Theorem
public import PiBaseLean.Theorems.T86.Theorem
public import PiBaseLean.Theorems.T87.Theorem
public import PiBaseLean.Theorems.T88.Theorem
public import PiBaseLean.Theorems.T89.Theorem
public import PiBaseLean.Theorems.T95.Theorem
public import PiBaseLean.Theorems.T96.Theorem
public import PiBaseLean.Theorems.T97.Theorem
public import PiBaseLean.Theorems.T98.Theorem
public import PiBaseLean.Theorems.T99.Theorem
public import PiBaseLean.Theorems.T100.Theorem
public import PiBaseLean.Theorems.T101.Theorem
public import PiBaseLean.Theorems.T104.Theorem
public import PiBaseLean.Theorems.T105.Theorem
public import PiBaseLean.Theorems.T106.Theorem
public import PiBaseLean.Theorems.T108.Theorem
public import PiBaseLean.Theorems.T112.Theorem
public import PiBaseLean.Theorems.T113.Theorem
public import PiBaseLean.Theorems.T115.Theorem
public import PiBaseLean.Theorems.T116.Theorem
public import PiBaseLean.Theorems.T117.Theorem
public import PiBaseLean.Theorems.T118.Theorem
public import PiBaseLean.Theorems.T119.Theorem
public import PiBaseLean.Theorems.T121.Theorem
public import PiBaseLean.Theorems.T122.Theorem
public import PiBaseLean.Theorems.T126.Theorem
public import PiBaseLean.Theorems.T128.Theorem
public import PiBaseLean.Theorems.T136.Theorem
public import PiBaseLean.Theorems.T139.Theorem
public import PiBaseLean.Theorems.T143.Theorem
public import PiBaseLean.Theorems.T144.Theorem
public import PiBaseLean.Theorems.T146.Theorem
public import PiBaseLean.Theorems.T147.Theorem
public import PiBaseLean.Theorems.T148.Theorem
public import PiBaseLean.Theorems.T149.Theorem
public import PiBaseLean.Theorems.T150.Theorem
public import PiBaseLean.Theorems.T151.Theorem
public import PiBaseLean.Theorems.T152.Theorem
public import PiBaseLean.Theorems.T153.Theorem
public import PiBaseLean.Theorems.T154.Theorem
public import PiBaseLean.Theorems.T156.Theorem
public import PiBaseLean.Theorems.T157.Theorem
public import PiBaseLean.Theorems.T158.Theorem
public import PiBaseLean.Theorems.T159.Theorem
public import PiBaseLean.Theorems.T160.Theorem
public import PiBaseLean.Theorems.T169.Theorem
public import PiBaseLean.Theorems.T176.Theorem
public import PiBaseLean.Theorems.T182.Theorem
public import PiBaseLean.Theorems.T183.Theorem
public import PiBaseLean.Theorems.T184.Theorem
public import PiBaseLean.Theorems.T187.Theorem
public import PiBaseLean.Theorems.T190.Theorem
public import PiBaseLean.Theorems.T191.Theorem
public import PiBaseLean.Theorems.T193.Theorem
public import PiBaseLean.Theorems.T197.Theorem
public import PiBaseLean.Theorems.T199.Theorem
public import PiBaseLean.Theorems.T200.Theorem
public import PiBaseLean.Theorems.T201.Theorem
public import PiBaseLean.Theorems.T204.Theorem
public import PiBaseLean.Theorems.T205.Theorem
public import PiBaseLean.Theorems.T208.Theorem
public import PiBaseLean.Theorems.T212.Theorem
public import PiBaseLean.Theorems.T221.Theorem
public import PiBaseLean.Theorems.T234.Theorem
public import PiBaseLean.Theorems.T241.Theorem
public import PiBaseLean.Theorems.T245.Theorem
public import PiBaseLean.Theorems.T246.Theorem
public import PiBaseLean.Theorems.T247.Theorem
public import PiBaseLean.Theorems.T248.Theorem
public import PiBaseLean.Theorems.T249.Theorem
public import PiBaseLean.Theorems.T250.Theorem
public import PiBaseLean.Theorems.T253.Theorem
public import PiBaseLean.Theorems.T254.Theorem
public import PiBaseLean.Theorems.T256.Theorem
public import PiBaseLean.Theorems.T257.Theorem
public import PiBaseLean.Theorems.T262.Theorem
public import PiBaseLean.Theorems.T264.Theorem
public import PiBaseLean.Theorems.T265.Theorem
public import PiBaseLean.Theorems.T266.Theorem
public import PiBaseLean.Theorems.T267.Theorem
public import PiBaseLean.Theorems.T268.Theorem
public import PiBaseLean.Theorems.T270.Theorem
public import PiBaseLean.Theorems.T281.Theorem
public import PiBaseLean.Theorems.T282.Theorem
public import PiBaseLean.Theorems.T283.Theorem
public import PiBaseLean.Theorems.T285.Theorem
public import PiBaseLean.Theorems.T286.Theorem
public import PiBaseLean.Theorems.T287.Theorem
public import PiBaseLean.Theorems.T288.Theorem
public import PiBaseLean.Theorems.T295.Theorem
public import PiBaseLean.Theorems.T303.Theorem
public import PiBaseLean.Theorems.T304.Theorem
public import PiBaseLean.Theorems.T306.Theorem
public import PiBaseLean.Theorems.T308.Theorem
public import PiBaseLean.Theorems.T325.Theorem
public import PiBaseLean.Theorems.T335.Theorem
public import PiBaseLean.Theorems.T336.Theorem
public import PiBaseLean.Theorems.T337.Theorem
public import PiBaseLean.Theorems.T338.Theorem
public import PiBaseLean.Theorems.T339.Theorem
public import PiBaseLean.Theorems.T346.Theorem
public import PiBaseLean.Theorems.T350.Theorem
public import PiBaseLean.Theorems.T359.Theorem
public import PiBaseLean.Theorems.T360.Theorem
public import PiBaseLean.Theorems.T361.Theorem
public import PiBaseLean.Theorems.T362.Theorem
public import PiBaseLean.Theorems.T390.Theorem
public import PiBaseLean.Theorems.T391.Theorem
public import PiBaseLean.Theorems.T401.Theorem
public import PiBaseLean.Theorems.T406.Theorem
public import PiBaseLean.Theorems.T407.Theorem
public import PiBaseLean.Theorems.T410.Theorem
public import PiBaseLean.Theorems.T419.Theorem
public import PiBaseLean.Theorems.T428.Theorem
public import PiBaseLean.Theorems.T430.Theorem
public import PiBaseLean.Theorems.T431.Theorem
public import PiBaseLean.Theorems.T440.Theorem
public import PiBaseLean.Theorems.T446.Theorem
public import PiBaseLean.Theorems.T448.Theorem
public import PiBaseLean.Theorems.T452.Theorem
public import PiBaseLean.Theorems.T454.Theorem
public import PiBaseLean.Theorems.T455.Theorem
public import PiBaseLean.Theorems.T456.Theorem
public import PiBaseLean.Theorems.T457.Theorem
public import PiBaseLean.Theorems.T468.Theorem
public import PiBaseLean.Theorems.T480.Theorem
public import PiBaseLean.Theorems.T481.Theorem
public import PiBaseLean.Theorems.T482.Theorem
public import PiBaseLean.Theorems.T483.Theorem
public import PiBaseLean.Theorems.T484.Theorem
public import PiBaseLean.Theorems.T500.Theorem
public import PiBaseLean.Theorems.T501.Theorem
public import PiBaseLean.Theorems.T502.Theorem
public import PiBaseLean.Theorems.T504.Theorem
public import PiBaseLean.Theorems.T505.Theorem
public import PiBaseLean.Theorems.T510.Theorem
public import PiBaseLean.Theorems.T511.Theorem
public import PiBaseLean.Theorems.T519.Theorem
public import PiBaseLean.Theorems.T527.Theorem
public import PiBaseLean.Theorems.T529.Theorem
public import PiBaseLean.Theorems.T535.Theorem
public import PiBaseLean.Theorems.T558.Theorem
public import PiBaseLean.Theorems.T559.Theorem
public import PiBaseLean.Theorems.T561.Theorem
public import PiBaseLean.Theorems.T564.Theorem
public import PiBaseLean.Theorems.T571.Theorem
public import PiBaseLean.Theorems.T572.Theorem
public import PiBaseLean.Theorems.T573.Theorem
public import PiBaseLean.Theorems.T583.Theorem
public import PiBaseLean.Theorems.T584.Theorem
public import PiBaseLean.Theorems.T586.Theorem
public import PiBaseLean.Theorems.T587.Theorem
public import PiBaseLean.Theorems.T590.Theorem
public import PiBaseLean.Theorems.T594.Theorem
public import PiBaseLean.Theorems.T610.Theorem
public import PiBaseLean.Theorems.T620.Theorem
public import PiBaseLean.Theorems.T621.Theorem
public import PiBaseLean.Theorems.T624.Theorem
public import PiBaseLean.Theorems.T630.Theorem
public import PiBaseLean.Theorems.T635.Theorem
public import PiBaseLean.Theorems.T649.Theorem
public import PiBaseLean.Theorems.T650.Theorem
public import PiBaseLean.Theorems.T652.Theorem
public import PiBaseLean.Theorems.T653.Theorem
public import PiBaseLean.Theorems.T654.Theorem
public import PiBaseLean.Theorems.T655.Theorem
public import PiBaseLean.Theorems.T657.Theorem
public import PiBaseLean.Theorems.T665.Theorem
public import PiBaseLean.Theorems.T693.Theorem
public import PiBaseLean.Theorems.T703.Theorem
public import PiBaseLean.Theorems.T704.Theorem
public import PiBaseLean.Theorems.T710.Theorem
public import PiBaseLean.Theorems.T715.Theorem
public import PiBaseLean.Theorems.T716.Theorem
public import PiBaseLean.Theorems.T717.Theorem
public import PiBaseLean.Theorems.T733.Theorem
public import PiBaseLean.Theorems.T735.Theorem
public import PiBaseLean.Theorems.T736.Theorem
public import PiBaseLean.Theorems.T740.Theorem
public import PiBaseLean.Theorems.T744.Theorem
public import PiBaseLean.Theorems.T750.Theorem
public import PiBaseLean.Theorems.T759.Theorem
public import PiBaseLean.Theorems.T765.Theorem
public import PiBaseLean.Theorems.T770.Theorem
public import PiBaseLean.Theorems.T779.Theorem
public import PiBaseLean.Theorems.T782.Theorem
public import PiBaseLean.Theorems.T790.Theorem
public import PiBaseLean.Theorems.T802.Theorem
public import PiBaseLean.Theorems.T803.Theorem
public import PiBaseLean.Theorems.T817.Theorem
public import PiBaseLean.Theorems.T818.Theorem
public import PiBaseLean.Theorems.T834.Theorem
public import PiBaseLean.Theorems.T840.Theorem
public import PiBaseLean.Theorems.T853.Theorem
public import PiBaseLean.Theorems.T858.Theorem
public import PiBaseLean.Theorems.T859.Theorem
public import PiBaseLean.Theorems.T860.Theorem
public import PiBaseLean.Theorems.T861.Theorem
public import PiBaseLean.Theorems.T862.Theorem
public import PiBaseLean.Theorems.T863.Theorem
public import PiBaseLean.Theorems.T864.Theorem
public import PiBaseLean.Theorems.T865.Theorem

/-!
# Statements checked against the π-base snapshot

Each `example` below restates, directly from `data/pibase.json`, the implication that
π-base records under a given uid, and discharges it with the formalization filed under
that uid. A `T<n>` whose type is not π-base's `T<n>` fails to elaborate here, so the
correspondence between this library and the database is checked by the kernel.

This file is generated. To extend it, formalize a theorem; it is picked up automatically.

9 formalized theorems are deliberately absent: their statements disagree
with the uid they are filed under, and are being resolved separately. They are listed,
with both statements, in `scripts/gen_statement_check.py`. See https://github.com/felixpernegger/pibase-lean/issues/1324.
-/

namespace PiBase.Formal

example : P16 ≤ P19 := T1
example : P19 ≤ P21 := T2
example : P20 ≤ P19 := T3
example : P19 ≤ P22 := T4
example : P24 ≤ P23 := T7
example : P25 ≤ P23 := T8
example : P16 ≤ P25 := T9
example : P183 ≤ P182 := T11
example : P16 ≤ P145 := T13
example : P30 ≤ P31 := T14
example : P26 ≤ P29 := T21
example : P136 ⊓ P57 ≤ P183 := T22
example : P124 ≤ P123 := T25
example : P23 ⊓ P134 ≤ P12 := T27
example : P123 ⊓ P3 ⊓ P27 ≤ P124 := T31
example : P4 ≤ P3 := T32
example : P5 ≤ P4 := T33
example : P118 ≤ P117 := T34
example : P12 ≤ P11 := T35
example : P14 ≤ P13 := T36
example : P13 ⊓ P135 ≤ P12 := T37
example : P40 ≤ P37 := T38
example : P38 ≤ P37 := T39
example : P37 ≤ P36 := T40
example : P45 ≤ P137ᶜ := T41
example : P52 ≤ P2 := T42
example : P2 ⊓ P51 ≤ P47 := T43
example : P49 ⊓ P3 ≤ P48 := T45
example : P48 ≤ P47 := T46
example : P47 ≤ P46 := T47
example : P48 ≤ P9 := T48
example : P46 ≤ P2 := T49
example : P39 ≤ P41 := T51
example : P47 ⊓ P125 ≤ P36ᶜ := T52
example : P74 ≤ P182 := T55
example : P23 ≤ P140 := T58
example : P79 ≤ P141 := T59
example : P140 ⊓ P170 ≤ P142 := T60
example : P182 ⊓ P5 ≤ P74 := T61
example : P43 ≤ P42 := T63
example : P42 ≤ P41 := T64
example : P133 ≤ P154 := T66
example : P57 ≤ P58 := T67
example : P58 ≤ P163 := T68
example : P57 ≤ P17 := T74
example : P60 ≤ P22 := T76
example : P55 ≤ P53 := T77
example : P44 ≤ P36 := T78
example : P23 ⊓ P100 ≤ P24 := T81
example : P177 ≤ P5 := T84
example : P52 ≤ P55 := T85
example : P9 ≤ P4 := T86
example : P40 ≤ P218 := T87
example : P37 ⊓ P125 ≤ P46ᶜ := T88
example : P233 ⊓ P46 ≤ P52 := T89
example : P36 ⊓ P233 ≤ P37 := T95
example : P39 ≤ P49 := T96
example : P49 ⊓ P36 ≤ P39 := T97
example : P7 ≤ P2 := T98
example : P2 ⊓ P13 ≤ P7 := T99
example : P8 ≤ P2 := T100
example : P2 ⊓ P14 ≤ P8 := T101
example : P35 ≤ P2 := T104
example : P2 ⊓ P34 ≤ P35 := T105
example : P18 ⊓ P19 ≤ P16 := T106
example : P234 ⊓ P47 ≤ P52 := T108
example : P8 ≤ P7 := T112
example : P7 ≤ P6 := T113
example : P6 ≤ P5 := T115
example : P179 ≤ P183 := T116
example : P183 ⊓ P5 ≤ P179 := T117
example : P3 ≤ P2 := T118
example : P2 ≤ P1 := T119
example : P16 ≤ P17 := T121
example : P17 ≤ P18 := T122
example : P16 ⊓ P3 ⊓ P49 ≤ P119 := T126
example : P18 ≤ P62 := T128
example : P23 ⊓ P11 ≤ P64 := T136
example : P65 ≤ P163 := T139
example : P126 ≤ P1 := T143
example : P52 ≤ P126 := T144
example : P5 ≤ P11 := T146
example : P177 ≤ P117 := T147
example : P11 ⊓ P1 ≤ P5 := T148
example : P6 ≤ P12 := T149
example : P117 ⊓ P5 ≤ P177 := T150
example : P12 ⊓ P1 ≤ P6 := T151
example : P67 ≤ P2 := T152
example : P2 ⊓ P15 ≤ P67 := T153
example : P67 ≤ P8 := T154
example : P15 ≤ P14 := T156
example : P127 ≤ P7 := T157
example : P127 ≤ P32ᶜ := T158
example : P7 ⊓ P32ᶜ ≤ P127 := T159
example : P68 ≤ P66 := T160
example : P51 ≤ P1 := T169
example : P75 ≤ P73 := T176
example : P178 ≤ P118 := T182
example : P28 ≤ P80 := T183
example : P80 ≤ P79 := T184
example : P78 ≤ P57 := T187
example : P114 ≤ P163 := T190
example : P114 ≤ P57ᶜ := T191
example : P3 ≤ P84 := T193
example : P118 ⊓ P5 ≤ P178 := T197
example : P116 ≤ P26 := T199
example : P116 ≤ P55 := T200
example : P26 ⊓ P55 ≤ P116 := T201
example : P52 ≤ P86 := T204
example : P172 ≤ P173 := T205
example : P129 ⊓ P125 ≤ P139ᶜ := T208
example : P57 ⊓ P28 ≤ P27 := T212
example : P168 ≤ P2 := T221
example : P103 ≤ P100 := T234
example : P179 ≤ P74 := T241
example : P130 ≤ P23 := T245
example : P23 ⊓ P11 ≤ P130 := T246
example : P52 ⊓ P129 ≤ P125ᶜ := T247
example : P125ᶜ ≤ P52 := T248
example : P125ᶜ ≤ P129 := T249
example : P78ᶜ ≤ P125 := T250
example : P125 ⊓ P1 ≤ P129ᶜ := T253
example : P131 ≤ P18 := T254
example : P15 ≤ P132 := T256
example : P13 ⊓ P132 ≤ P15 := T257
example : P134 ⊓ P39 ≤ P129 := T262
example : P53 ≤ P121 := T264
example : P121 ⊓ P1 ≤ P53 := T265
example : P78 ≤ P94 := T266
example : P90 ⊓ P2 ≤ P52 := T267
example : P121 ≤ P15 := T268
example : P27 ≤ P28 := T270
example : P3 ≤ P134 := T281
example : P11 ≤ P134 := T282
example : P134 ⊓ P1 ≤ P3 := T283
example : P90 ≤ P28 := T285
example : P134 ≤ P135 := T286
example : P2 ≤ P135 := T287
example : P135 ⊓ P1 ≤ P2 := T288
example : P125 ≤ P137ᶜ := T295
example : P136 ⊓ P16 ≤ P78 := T303
example : P136 ⊓ P17 ≤ P57 := T304
example : P51 ⊓ P137ᶜ ≤ P139 := T306
example : P135 ⊓ P139 ⊓ P125 ≤ P36ᶜ := T308
example : P141 ≤ P140 := T325
example : P7 ≤ P13 := T335
example : P8 ≤ P14 := T336
example : P35 ≤ P34 := T337
example : P67 ≤ P15 := T338
example : P75 ≤ P16 := T339
example : P87 ≤ P137ᶜ := T346
example : P90 ≤ P147 := T350
example : P150 ≤ P153 := T359
example : P149 ≤ P18 := T360
example : P150 ≤ P68 := T361
example : P153 ≤ P66 := T362
example : P163 ≤ P59 := T390
example : P163 ⊓ P58ᶜ ≤ P65 := T391
example : P13 ≤ P165 := T401
example : P165 ⊓ P57 ≤ P13 := T406
example : P53 ≤ P112 := T407
example : P166 ≤ P112 := T410
example : P169 ≤ P2 := T419
example : P175 ≤ P125 := T428
example : P176 ≤ P175 := T430
example : P78ᶜ ≤ P176 := T431
example : P180 ≤ P26 := T440
example : P89 ≤ P137ᶜ := T446
example : P129 ≤ P185 := T448
example : P204 ≤ P36 := T452
example : P181 ≤ P57 := T454
example : P181 ≤ P78ᶜ := T455
example : P57 ⊓ P78ᶜ ≤ P181 := T456
example : P77 ≤ P16 := T457
example : P185 ⊓ P36 ≤ P129 := T468
example : P16 ⊓ P36 ⊓ P3 ≤ P188 := T480
example : P188 ≤ P3 := T481
example : P188 ≤ P16 := T482
example : P188 ≤ P36 := T483
example : P189 ≤ P36 := T484
example : P191 ≤ P2 := T500
example : P28 ⊓ P2 ≤ P191 := T501
example : P132 ⊓ P2 ≤ P191 := T502
example : P92 ≤ P98 := T504
example : P98 ⊓ P170 ≤ P92 := T505
example : P147 ⊓ P191 ≤ P52 := T510
example : P73 ≤ P192 := T511
example : P134 ≤ P192 := T519
example : P75 ≤ P130 := T527
example : P16 ⊓ P3 ⊓ P47 ≤ P195 := T529
example : P123 ≤ P122 := T535
example : P204 ≤ P175 := T558
example : P198 ⊓ P52 ≤ P57 := T559
example : P197 ≤ P198 := T561
example : P94 ≤ P93 := T564
example : P203 ≤ P52ᶜ := T571
example : P203 ≤ P126 := T572
example : P203 ≤ P51 := T573
example : P199 ≤ P200 := T583
example : P199 ≤ P137ᶜ := T584
example : P31 ≤ P83 := T586
example : P18 ≤ P83 := T587
example : P200 ≤ P37 := T590
example : P192 ⊓ P39 ⊓ P137ᶜ ≤ P201 := T594
example : P63 ≤ P6 := T610
example : P196 ≤ P204ᶜ := T620
example : P107 ≤ P137ᶜ := T621
example : P102 ≤ P104 := T624
example : P2 ⊓ P137ᶜ ≤ P107 := T630
example : P205 ≤ P204 := T635
example : P126 ⊓ P137ᶜ ≤ P107 := T649
example : P208 ≤ P16 := T650
example : P208 ≤ P130 := T652
example : P30 ≤ P105 := T653
example : P18 ≤ P105 := T654
example : P105 ≤ P83 := T655
example : P208 ≤ P131 := T657
example : P108 ≤ P88 := T665
example : P49 ≤ P85 := T693
example : P95 ≤ P38 := T703
example : P96 ≤ P43 := T704
example : P110 ≤ P28 := T710
example : P113 ≤ P110 := T715
example : P113 ≤ P5 := T716
example : P110 ⊓ P5 ≤ P113 := T717
example : P210 ≤ P211 := T733
example : P212 ≤ P213 := T735
example : P213 ≤ P214 := T736
example : P215 ≤ P162 := T740
example : P216 ≤ P30 := T744
example : P133 ≤ P120 := T750
example : P155 ≤ P123 := T759
example : P218 ≤ P13 := T765
example : P220 ≤ P53 := T770
example : P222 ≤ P2 := T779
example : P52 ⊓ P78 ≤ P222 := T782
example : P93 ⊓ P2 ≤ P191 := T790
example : P119 ≤ P195 := T802
example : P119 ≤ P49 := T803
example : P52 ≤ P219 := T817
example : P78 ≤ P219 := T818
example : P227 ≤ P58ᶜ := T834
example : P228 ≤ P79 := T840
example : P230 ≤ P231 := T853
example : P200 ≤ P231 := T858
example : P231 ≤ P233 := T859
example : P37 ≤ P233 := T860
example : P42 ≤ P233 := T861
example : P233 ≤ P234 := T862
example : P41 ≤ P234 := T863
example : P36 ≤ P234 := T864
example : P51 ≤ P73 := T865

end PiBase.Formal
