module

public import Mathlib
public import PiBaseLean.AdditionalDefs
public import PiBaseLean.Properties.Bundled.Basic
public import PiBaseLean.Properties.Bundled.Defs
public import PiBaseLean.Properties.P1.Defs
public import PiBaseLean.Properties.P2.Defs
public import PiBaseLean.Properties.P3.Defs
public import PiBaseLean.Properties.P4.Defs
public import PiBaseLean.Properties.P5.Defs
public import PiBaseLean.Properties.P6.Defs
public import PiBaseLean.Properties.P7.Defs
public import PiBaseLean.Properties.P8.Defs
public import PiBaseLean.Properties.P9.Defs
public import PiBaseLean.Properties.P10.Defs
public import PiBaseLean.Properties.P11.Defs
public import PiBaseLean.Properties.P12.Defs
public import PiBaseLean.Properties.P13.Defs
public import PiBaseLean.Properties.P14.Defs
public import PiBaseLean.Properties.P15.Defs
public import PiBaseLean.Properties.P16.Defs
public import PiBaseLean.Properties.P17.Defs
public import PiBaseLean.Properties.P18.Defs
public import PiBaseLean.Properties.P19.Defs
public import PiBaseLean.Properties.P20.Defs
public import PiBaseLean.Properties.P21.Defs
public import PiBaseLean.Properties.P22.Defs
public import PiBaseLean.Properties.P23.Defs
public import PiBaseLean.Properties.P24.Defs
public import PiBaseLean.Properties.P25.Defs
public import PiBaseLean.Properties.P26.Defs
public import PiBaseLean.Properties.P27.Defs
public import PiBaseLean.Properties.P28.Defs
public import PiBaseLean.Properties.P29.Defs
public import PiBaseLean.Properties.P30.Defs
public import PiBaseLean.Properties.P31.Defs
public import PiBaseLean.Properties.P32.Defs
public import PiBaseLean.Properties.P33.Defs
public import PiBaseLean.Properties.P34.Defs
public import PiBaseLean.Properties.P35.Defs
public import PiBaseLean.Properties.P36.Defs
public import PiBaseLean.Properties.P37.Defs
public import PiBaseLean.Properties.P38.Defs
public import PiBaseLean.Properties.P39.Defs
public import PiBaseLean.Properties.P40.Defs
public import PiBaseLean.Properties.P41.Defs
public import PiBaseLean.Properties.P42.Defs
public import PiBaseLean.Properties.P43.Defs
public import PiBaseLean.Properties.P44.Defs
public import PiBaseLean.Properties.P45.Defs
public import PiBaseLean.Properties.P46.Defs
public import PiBaseLean.Properties.P47.Defs
public import PiBaseLean.Properties.P48.Defs
public import PiBaseLean.Properties.P49.Defs
public import PiBaseLean.Properties.P50.Defs
public import PiBaseLean.Properties.P51.Defs
public import PiBaseLean.Properties.P52.Defs
public import PiBaseLean.Properties.P53.Defs
public import PiBaseLean.Properties.P54.Defs
public import PiBaseLean.Properties.P55.Defs
public import PiBaseLean.Properties.P56.Defs
public import PiBaseLean.Properties.P57.Defs
public import PiBaseLean.Properties.P58.Defs
public import PiBaseLean.Properties.P59.Defs
public import PiBaseLean.Properties.P60.Defs
public import PiBaseLean.Properties.P61.Defs
public import PiBaseLean.Properties.P62.Defs
public import PiBaseLean.Properties.P63.Defs
public import PiBaseLean.Properties.P64.Defs
public import PiBaseLean.Properties.P65.Defs
public import PiBaseLean.Properties.P66.Defs
public import PiBaseLean.Properties.P67.Defs
public import PiBaseLean.Properties.P68.Defs
public import PiBaseLean.Properties.P71.Defs
public import PiBaseLean.Properties.P73.Defs
public import PiBaseLean.Properties.P74.Defs
public import PiBaseLean.Properties.P75.Defs
public import PiBaseLean.Properties.P77.Defs
public import PiBaseLean.Properties.P78.Defs
public import PiBaseLean.Properties.P79.Defs
public import PiBaseLean.Properties.P80.Defs
public import PiBaseLean.Properties.P81.Defs
public import PiBaseLean.Properties.P82.Defs
public import PiBaseLean.Properties.P83.Defs
public import PiBaseLean.Properties.P84.Defs
public import PiBaseLean.Properties.P85.Defs
public import PiBaseLean.Properties.P86.Defs
public import PiBaseLean.Properties.P87.Defs
public import PiBaseLean.Properties.P88.Defs
public import PiBaseLean.Properties.P89.Defs
public import PiBaseLean.Properties.P90.Defs
public import PiBaseLean.Properties.P92.Defs
public import PiBaseLean.Properties.P93.Defs
public import PiBaseLean.Properties.P94.Defs
public import PiBaseLean.Properties.P95.Defs
public import PiBaseLean.Properties.P96.Defs
public import PiBaseLean.Properties.P97.Defs
public import PiBaseLean.Properties.P98.Defs
public import PiBaseLean.Properties.P99.Defs
public import PiBaseLean.Properties.P100.Defs
public import PiBaseLean.Properties.P101.Defs
public import PiBaseLean.Properties.P102.Defs
public import PiBaseLean.Properties.P103.Defs
public import PiBaseLean.Properties.P104.Defs
public import PiBaseLean.Properties.P105.Defs
public import PiBaseLean.Properties.P106.Defs
public import PiBaseLean.Properties.P107.Defs
public import PiBaseLean.Properties.P108.Defs
public import PiBaseLean.Properties.P109.Defs
public import PiBaseLean.Properties.P110.Defs
public import PiBaseLean.Properties.P111.Defs
public import PiBaseLean.Properties.P112.Defs
public import PiBaseLean.Properties.P113.Defs
public import PiBaseLean.Properties.P114.Defs
public import PiBaseLean.Properties.P115.Defs
public import PiBaseLean.Properties.P116.Defs
public import PiBaseLean.Properties.P117.Defs
public import PiBaseLean.Properties.P118.Defs
public import PiBaseLean.Properties.P119.Defs
public import PiBaseLean.Properties.P120.Defs
public import PiBaseLean.Properties.P121.Defs
public import PiBaseLean.Properties.P122.Defs
public import PiBaseLean.Properties.P123.Defs
public import PiBaseLean.Properties.P124.Defs
public import PiBaseLean.Properties.P125.Defs
public import PiBaseLean.Properties.P126.Defs
public import PiBaseLean.Properties.P127.Defs
public import PiBaseLean.Properties.P128.Defs
public import PiBaseLean.Properties.P129.Defs
public import PiBaseLean.Properties.P130.Defs
public import PiBaseLean.Properties.P131.Defs
public import PiBaseLean.Properties.P132.Defs
public import PiBaseLean.Properties.P133.Defs
public import PiBaseLean.Properties.P134.Defs
public import PiBaseLean.Properties.P135.Defs
public import PiBaseLean.Properties.P136.Defs
public import PiBaseLean.Properties.P137.Defs
public import PiBaseLean.Properties.P138.Defs
public import PiBaseLean.Properties.P139.Defs
public import PiBaseLean.Properties.P140.Defs
public import PiBaseLean.Properties.P141.Defs
public import PiBaseLean.Properties.P142.Defs
public import PiBaseLean.Properties.P143.Defs
public import PiBaseLean.Properties.P144.Defs
public import PiBaseLean.Properties.P145.Defs
public import PiBaseLean.Properties.P146.Defs
public import PiBaseLean.Properties.P147.Defs
public import PiBaseLean.Properties.P148.Defs
public import PiBaseLean.Properties.P149.Defs
public import PiBaseLean.Properties.P150.Defs
public import PiBaseLean.Properties.P153.Defs
public import PiBaseLean.Properties.P154.Defs
public import PiBaseLean.Properties.P155.Defs
public import PiBaseLean.Properties.P162.Defs
public import PiBaseLean.Properties.P163.Defs
public import PiBaseLean.Properties.P165.Defs
public import PiBaseLean.Properties.P166.Defs
public import PiBaseLean.Properties.P167.Defs
public import PiBaseLean.Properties.P168.Defs
public import PiBaseLean.Properties.P169.Defs
public import PiBaseLean.Properties.P170.Defs
public import PiBaseLean.Properties.P171.Defs
public import PiBaseLean.Properties.P172.Defs
public import PiBaseLean.Properties.P173.Defs
public import PiBaseLean.Properties.P174.Defs
public import PiBaseLean.Properties.P175.Defs
public import PiBaseLean.Properties.P176.Defs
public import PiBaseLean.Properties.P177.Defs
public import PiBaseLean.Properties.P178.Defs
public import PiBaseLean.Properties.P179.Defs
public import PiBaseLean.Properties.P180.Defs
public import PiBaseLean.Properties.P181.Defs
public import PiBaseLean.Properties.P182.Defs
public import PiBaseLean.Properties.P183.Defs
public import PiBaseLean.Properties.P184.Defs
public import PiBaseLean.Properties.P185.Defs
public import PiBaseLean.Properties.P188.Defs
public import PiBaseLean.Properties.P189.Defs
public import PiBaseLean.Properties.P190.Defs
public import PiBaseLean.Properties.P191.Defs
public import PiBaseLean.Properties.P192.Defs
public import PiBaseLean.Properties.P193.Defs
public import PiBaseLean.Properties.P194.Defs
public import PiBaseLean.Properties.P195.Defs
public import PiBaseLean.Properties.P196.Defs
public import PiBaseLean.Properties.P197.Defs
public import PiBaseLean.Properties.P198.Defs
public import PiBaseLean.Properties.P199.Defs
public import PiBaseLean.Properties.P200.Defs
public import PiBaseLean.Properties.P201.Defs
public import PiBaseLean.Properties.P202.Defs
public import PiBaseLean.Properties.P203.Defs
public import PiBaseLean.Properties.P204.Defs
public import PiBaseLean.Properties.P205.Defs
public import PiBaseLean.Properties.P207.Defs
public import PiBaseLean.Properties.P208.Defs
public import PiBaseLean.Properties.P209.Defs
public import PiBaseLean.Properties.P210.Defs
public import PiBaseLean.Properties.P211.Defs
public import PiBaseLean.Properties.P212.Defs
public import PiBaseLean.Properties.P213.Defs
public import PiBaseLean.Properties.P214.Defs
public import PiBaseLean.Properties.P215.Defs
public import PiBaseLean.Properties.P216.Defs
public import PiBaseLean.Properties.P217.Defs
public import PiBaseLean.Properties.P218.Defs
public import PiBaseLean.Properties.P219.Defs
public import PiBaseLean.Properties.P220.Defs
public import PiBaseLean.Properties.P222.Defs
public import PiBaseLean.Properties.P226.Defs
public import PiBaseLean.Properties.P227.Defs
public import PiBaseLean.Properties.P228.Defs
public import PiBaseLean.Properties.P229.Defs
public import PiBaseLean.Properties.P230.Defs
public import PiBaseLean.Properties.P231.Defs
public import PiBaseLean.Properties.P232.Defs
public import PiBaseLean.Properties.P233.Defs
public import PiBaseLean.Properties.P234.Defs

universe u

open Topology

namespace PiBase

instance instStoneSpaceOfCompactSpaceOfT2SpaceOfTotallyDisconnectedSpace (X : Type u)
    [TopologicalSpace X] [h : CompactSapce X] [h' : T2Space X] [h'' : TotallyDisconectedSpace X] :
    StoneSpace X := by
  sorry

end PiBase
