module

-- This file is generated by scripts/gen_traits.py. Do not edit.
public import PiBaseLean.Spaces.S189.Lemmas
public import PiBaseLean.Properties.P1.Bundled
public import PiBaseLean.Properties.P2.Bundled
public import PiBaseLean.Properties.P3.Bundled
public import PiBaseLean.Properties.P4.Bundled
public import PiBaseLean.Properties.P5.Bundled
public import PiBaseLean.Properties.P6.Bundled
public import PiBaseLean.Properties.P7.Bundled
public import PiBaseLean.Properties.P8.Bundled
public import PiBaseLean.Properties.P11.Bundled
public import PiBaseLean.Properties.P12.Bundled
public import PiBaseLean.Properties.P13.Bundled
public import PiBaseLean.Properties.P14.Bundled
public import PiBaseLean.Properties.P15.Bundled
public import PiBaseLean.Properties.P53.Bundled
public import PiBaseLean.Properties.P55.Bundled
public import PiBaseLean.Properties.P67.Bundled
public import PiBaseLean.Properties.P84.Bundled
public import PiBaseLean.Properties.P86.Bundled
public import PiBaseLean.Properties.P112.Bundled
public import PiBaseLean.Properties.P121.Bundled
public import PiBaseLean.Properties.P125.Bundled
public import PiBaseLean.Properties.P126.Bundled
public import PiBaseLean.Properties.P132.Bundled
public import PiBaseLean.Properties.P134.Bundled
public import PiBaseLean.Properties.P135.Bundled
public import PiBaseLean.Properties.P165.Bundled
public import PiBaseLean.Properties.P191.Bundled
public import PiBaseLean.Properties.P192.Bundled
public import PiBaseLean.Properties.P219.Bundled
public import PiBaseLean.Theorems.T33.Theorem
public import PiBaseLean.Theorems.T36.Theorem
public import PiBaseLean.Theorems.T37.Theorem
public import PiBaseLean.Theorems.T42.Theorem
public import PiBaseLean.Theorems.T77.Theorem
public import PiBaseLean.Theorems.T85.Theorem
public import PiBaseLean.Theorems.T99.Theorem
public import PiBaseLean.Theorems.T113.Theorem
public import PiBaseLean.Theorems.T115.Theorem
public import PiBaseLean.Theorems.T119.Theorem
public import PiBaseLean.Theorems.T144.Theorem
public import PiBaseLean.Theorems.T146.Theorem
public import PiBaseLean.Theorems.T153.Theorem
public import PiBaseLean.Theorems.T154.Theorem
public import PiBaseLean.Theorems.T156.Theorem
public import PiBaseLean.Theorems.T193.Theorem
public import PiBaseLean.Theorems.T204.Theorem
public import PiBaseLean.Theorems.T256.Theorem
public import PiBaseLean.Theorems.T264.Theorem
public import PiBaseLean.Theorems.T268.Theorem
public import PiBaseLean.Theorems.T282.Theorem
public import PiBaseLean.Theorems.T283.Theorem
public import PiBaseLean.Theorems.T287.Theorem
public import PiBaseLean.Theorems.T401.Theorem
public import PiBaseLean.Theorems.T407.Theorem
public import PiBaseLean.Theorems.T428.Theorem
public import PiBaseLean.Theorems.T502.Theorem
public import PiBaseLean.Theorems.T519.Theorem
public import PiBaseLean.Theorems.T817.Theorem

@[expose] public section

namespace PiBase.Formal

theorem S189_P2 : P2 PiBase.S189 :=
  T42 PiBase.S189 inferInstance S189_P52

register_certificate S000189 P000002 true
  proof PiBase.Formal.S189_P2
  provenance derived
  assumptions []

theorem S189_P55 : P55 PiBase.S189 :=
  T85 PiBase.S189 inferInstance S189_P52

register_certificate S000189 P000055 true
  proof PiBase.Formal.S189_P55
  provenance derived
  assumptions []

theorem S189_P1 : P1 PiBase.S189 :=
  T119 PiBase.S189 inferInstance S189_P2

register_certificate S000189 P000001 true
  proof PiBase.Formal.S189_P1
  provenance derived
  assumptions []

theorem S189_P126 : P126 PiBase.S189 :=
  T144 PiBase.S189 inferInstance S189_P52

register_certificate S000189 P000126 true
  proof PiBase.Formal.S189_P126
  provenance derived
  assumptions []

theorem S189_P86 : P86 PiBase.S189 :=
  T204 PiBase.S189 inferInstance S189_P52

register_certificate S000189 P000086 true
  proof PiBase.Formal.S189_P86
  provenance derived
  assumptions []

theorem S189_P135 : P135 PiBase.S189 :=
  T287 PiBase.S189 inferInstance S189_P2

register_certificate S000189 P000135 true
  proof PiBase.Formal.S189_P135
  provenance derived
  assumptions []

theorem S189_P125 : P125 PiBase.S189 :=
  T428 PiBase.S189 inferInstance S189_P175

register_certificate S000189 P000125 true
  proof PiBase.Formal.S189_P125
  provenance derived
  assumptions []

theorem S189_P219 : P219 PiBase.S189 :=
  T817 PiBase.S189 inferInstance S189_P52

register_certificate S000189 P000219 true
  proof PiBase.Formal.S189_P219
  provenance derived
  assumptions []

theorem S189_P53 : P53 PiBase.S189 :=
  T77 PiBase.S189 inferInstance S189_P55

register_certificate S000189 P000053 true
  proof PiBase.Formal.S189_P53
  provenance derived
  assumptions []

theorem S189_P121 : P121 PiBase.S189 :=
  T264 PiBase.S189 inferInstance S189_P53

register_certificate S000189 P000121 true
  proof PiBase.Formal.S189_P121
  provenance derived
  assumptions []

theorem S189_P15 : P15 PiBase.S189 :=
  T268 PiBase.S189 inferInstance S189_P121

register_certificate S000189 P000015 true
  proof PiBase.Formal.S189_P15
  provenance derived
  assumptions []

theorem S189_P112 : P112 PiBase.S189 :=
  T407 PiBase.S189 inferInstance S189_P53

register_certificate S000189 P000112 true
  proof PiBase.Formal.S189_P112
  provenance derived
  assumptions []

theorem S189_P67 : P67 PiBase.S189 :=
  T153 PiBase.S189 inferInstance ⟨S189_P2, S189_P15⟩

register_certificate S000189 P000067 true
  proof PiBase.Formal.S189_P67
  provenance derived
  assumptions []

theorem S189_P8 : P8 PiBase.S189 :=
  T154 PiBase.S189 inferInstance S189_P67

register_certificate S000189 P000008 true
  proof PiBase.Formal.S189_P8
  provenance derived
  assumptions []

theorem S189_P14 : P14 PiBase.S189 :=
  T156 PiBase.S189 inferInstance S189_P15

register_certificate S000189 P000014 true
  proof PiBase.Formal.S189_P14
  provenance derived
  assumptions []

theorem S189_P132 : P132 PiBase.S189 :=
  T256 PiBase.S189 inferInstance S189_P15

register_certificate S000189 P000132 true
  proof PiBase.Formal.S189_P132
  provenance derived
  assumptions []

theorem S189_P191 : P191 PiBase.S189 :=
  T502 PiBase.S189 inferInstance ⟨S189_P132, S189_P2⟩

register_certificate S000189 P000191 true
  proof PiBase.Formal.S189_P191
  provenance derived
  assumptions []

theorem S189_P13 : P13 PiBase.S189 :=
  T36 PiBase.S189 inferInstance S189_P14

register_certificate S000189 P000013 true
  proof PiBase.Formal.S189_P13
  provenance derived
  assumptions []

theorem S189_P12 : P12 PiBase.S189 :=
  T37 PiBase.S189 inferInstance ⟨S189_P13, S189_P135⟩

register_certificate S000189 P000012 true
  proof PiBase.Formal.S189_P12
  provenance derived
  assumptions []

theorem S189_P7 : P7 PiBase.S189 :=
  T99 PiBase.S189 inferInstance ⟨S189_P2, S189_P13⟩

register_certificate S000189 P000007 true
  proof PiBase.Formal.S189_P7
  provenance derived
  assumptions []

theorem S189_P6 : P6 PiBase.S189 :=
  T113 PiBase.S189 inferInstance S189_P7

register_certificate S000189 P000006 true
  proof PiBase.Formal.S189_P6
  provenance derived
  assumptions []

theorem S189_P5 : P5 PiBase.S189 :=
  T115 PiBase.S189 inferInstance S189_P6

register_certificate S000189 P000005 true
  proof PiBase.Formal.S189_P5
  provenance derived
  assumptions []

theorem S189_P11 : P11 PiBase.S189 :=
  T146 PiBase.S189 inferInstance S189_P5

register_certificate S000189 P000011 true
  proof PiBase.Formal.S189_P11
  provenance derived
  assumptions []

theorem S189_P134 : P134 PiBase.S189 :=
  T282 PiBase.S189 inferInstance S189_P11

register_certificate S000189 P000134 true
  proof PiBase.Formal.S189_P134
  provenance derived
  assumptions []

theorem S189_P3 : P3 PiBase.S189 :=
  T283 PiBase.S189 inferInstance ⟨S189_P134, S189_P1⟩

register_certificate S000189 P000003 true
  proof PiBase.Formal.S189_P3
  provenance derived
  assumptions []

theorem S189_P165 : P165 PiBase.S189 :=
  T401 PiBase.S189 inferInstance S189_P13

register_certificate S000189 P000165 true
  proof PiBase.Formal.S189_P165
  provenance derived
  assumptions []

theorem S189_P192 : P192 PiBase.S189 :=
  T519 PiBase.S189 inferInstance S189_P134

register_certificate S000189 P000192 true
  proof PiBase.Formal.S189_P192
  provenance derived
  assumptions []

theorem S189_P4 : P4 PiBase.S189 :=
  T33 PiBase.S189 inferInstance S189_P5

register_certificate S000189 P000004 true
  proof PiBase.Formal.S189_P4
  provenance derived
  assumptions []

theorem S189_P84 : P84 PiBase.S189 :=
  T193 PiBase.S189 inferInstance S189_P3

register_certificate S000189 P000084 true
  proof PiBase.Formal.S189_P84
  provenance derived
  assumptions []

end PiBase.Formal
