module

-- This file is generated by scripts/gen_traits.py. Do not edit.
public import PiBaseLean.Spaces.S10.Lemmas
public import PiBaseLean.Properties.P1.Bundled
public import PiBaseLean.Properties.P51.Bundled
public import PiBaseLean.Properties.P73.Bundled
public import PiBaseLean.Properties.P126.Bundled
public import PiBaseLean.Properties.P176.Bundled
public import PiBaseLean.Properties.P192.Bundled
public import PiBaseLean.Properties.P204.Bundled
public import PiBaseLean.Properties.P205.Bundled
public import PiBaseLean.Theorems.T143.Theorem
public import PiBaseLean.Theorems.T430.Theorem
public import PiBaseLean.Theorems.T511.Theorem
public import PiBaseLean.Theorems.T558.Theorem
public import PiBaseLean.Theorems.T572.Theorem
public import PiBaseLean.Theorems.T573.Theorem
public import PiBaseLean.Theorems.T635.Theorem
public import PiBaseLean.Theorems.T865.Theorem

@[expose] public section

namespace PiBase.Formal

theorem S10_P176_not : ¬ P176 PiBase.S10 := by
  intro h
  exact S10_P175_not (T430 PiBase.S10 inferInstance h)

register_certificate S000010 P000176 false
  proof PiBase.Formal.S10_P176_not
  provenance derived
  assumptions []

theorem S10_P204_not : ¬ P204 PiBase.S10 := by
  intro h
  exact S10_P175_not (T558 PiBase.S10 inferInstance h)

register_certificate S000010 P000204 false
  proof PiBase.Formal.S10_P204_not
  provenance derived
  assumptions []

theorem S10_P126 : P126 PiBase.S10 :=
  T572 PiBase.S10 inferInstance S10_P203

register_certificate S000010 P000126 true
  proof PiBase.Formal.S10_P126
  provenance derived
  assumptions []

theorem S10_P51 : P51 PiBase.S10 :=
  T573 PiBase.S10 inferInstance S10_P203

register_certificate S000010 P000051 true
  proof PiBase.Formal.S10_P51
  provenance derived
  assumptions []

theorem S10_P205_not : ¬ P205 PiBase.S10 := by
  intro h
  exact S10_P204_not (T635 PiBase.S10 inferInstance h)

register_certificate S000010 P000205 false
  proof PiBase.Formal.S10_P205_not
  provenance derived
  assumptions []

theorem S10_P73 : P73 PiBase.S10 :=
  T865 PiBase.S10 inferInstance S10_P51

register_certificate S000010 P000073 true
  proof PiBase.Formal.S10_P73
  provenance derived
  assumptions []

theorem S10_P1 : P1 PiBase.S10 :=
  T143 PiBase.S10 inferInstance S10_P126

register_certificate S000010 P000001 true
  proof PiBase.Formal.S10_P1
  provenance derived
  assumptions []

theorem S10_P192 : P192 PiBase.S10 :=
  T511 PiBase.S10 inferInstance S10_P73

register_certificate S000010 P000192 true
  proof PiBase.Formal.S10_P192
  provenance derived
  assumptions []

end PiBase.Formal
