#!/usr/bin/env python3
"""Scaffold and validate numbered Pi-Base space modules.

Usage:
    python3 scripts/gen_spaces.py S000147
    python3 scripts/gen_spaces.py
    python3 scripts/gen_spaces.py --check

Providing an ID creates exactly one unpadded ``S<N>`` three-file module scaffold.
A run without an ID only regenerates ``PiBaseLean/Spaces/All.lean``. ``--check``
performs no writes and fails when the tree is invalid or the aggregate is stale.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Iterable, Sequence

ROOT = Path(__file__).resolve().parent.parent
LEAN_ROOT = Path(
    os.environ.get("PIBASE_LEAN_SOURCE", os.environ.get("FELIX_REPO_PATH", ROOT))
).resolve()
SPACES_RELATIVE = Path("PiBaseLean") / "Spaces"
ALL_HEADER = "-- This file is generated by scripts/gen_spaces.py.\n"
ALL_AUDIT_IMPORT = "public meta import PiBaseLean.Audit.Spaces.Audit\n"
GENERATED_HEADER = "-- This file is generated by scripts/gen_traits.py. Do not edit.\n"
_PROOF_DEBT = re.compile(r"\b(?:sorry|admit)\b|^\s*axiom\b", re.MULTILINE)

_SPACE_ID = re.compile(r"(?:[Ss])?(\d+)")
_SPACE_DIR = re.compile(r"S(\d+)")
_IMPORT = re.compile(
    r"^\s*(?:public\s+)?import\s+PiBaseLean\.Spaces\.S(\d+)(?:\.([^\s]+))?\s*$",
    re.MULTILINE,
)


class SpaceValidationError(ValueError):
    """An expected space-tree convention was violated."""


def normalize_space_id(value: str | int) -> str:
    """Return an unpadded Lean ID such as ``S147``."""
    text = str(value).strip()
    match = _SPACE_ID.fullmatch(text)
    if match is None:
        raise SpaceValidationError(
            f"invalid space ID {value!r}; expected digits or S followed by digits"
        )
    number = int(match.group(1))
    if number <= 0:
        raise SpaceValidationError(f"invalid space ID {value!r}; IDs must be positive")
    return f"S{number}"


def spaces_root(lean_root: Path = LEAN_ROOT) -> Path:
    return Path(lean_root).resolve() / SPACES_RELATIVE


def _defs_template(space_id: str) -> str:
    return f"""module

public import Mathlib.Topology.Homeomorph.Defs

@[expose] public section

namespace PiBase

/-- Pi-Base {space_id}. Replace this scaffold with the catalog carrier. -/
def {space_id} : Type := by
  sorry

instance : TopologicalSpace {space_id} := by
  sorry

/-- The canonical presentation of Pi-Base {space_id}. Replace the target as needed. -/
def {space_id}_canonicalHomeomorph : {space_id} ≃ₜ {space_id} :=
  Homeomorph.refl {space_id}

end PiBase
"""


def _lemmas_template(space_id: str) -> str:
    return f"""module

public import PiBaseLean.Spaces.{space_id}.Defs

@[expose] public section

namespace PiBase.Formal

-- Add direct trait theorems and certificate registrations here.

end PiBase.Formal
"""


def _generated_template(space_id: str) -> str:
    return f"""module

{GENERATED_HEADER}public import PiBaseLean.Spaces.{space_id}.Lemmas

@[expose] public section

namespace PiBase.Formal

/- No derived declarations. -/

end PiBase.Formal
"""


def scaffold_space(
    value: str | int, lean_root: Path = LEAN_ROOT
) -> tuple[Path, Path, Path, bool]:
    """Create one space scaffold, or leave an existing complete scaffold untouched.

    Returns ``(Defs.lean, Lemmas.lean, Generated.lean, created)``. An existing
    incomplete or otherwise populated target directory is rejected so unrelated
    work is never silently completed or overwritten.
    """
    space_id = normalize_space_id(value)
    root = spaces_root(lean_root)
    target = root / space_id
    defs = target / "Defs.lean"
    lemmas = target / "Lemmas.lean"
    generated = target / "Generated.lean"

    if target.exists():
        if not target.is_dir():
            raise SpaceValidationError(f"space path is not a directory: {target}")
        if defs.is_file() and lemmas.is_file() and generated.is_file():
            return defs, lemmas, generated, False
        raise SpaceValidationError(
            f"refusing to modify existing incomplete space directory: {target}"
        )

    root.mkdir(parents=True, exist_ok=True)
    target.mkdir()
    created: list[Path] = []
    try:
        defs.write_text(_defs_template(space_id), encoding="utf-8")
        created.append(defs)
        lemmas.write_text(_lemmas_template(space_id), encoding="utf-8")
        created.append(lemmas)
        generated.write_text(_generated_template(space_id), encoding="utf-8")
        created.append(generated)
    except BaseException:
        for path in reversed(created):
            path.unlink(missing_ok=True)
        target.rmdir()
        raise
    return defs, lemmas, generated, True


def _numbered_directories(root: Path) -> Iterable[tuple[int, Path]]:
    if not root.exists():
        return
    for path in root.iterdir():
        if path.name in {"All.lean", "Constructions"}:
            continue
        match = _SPACE_DIR.fullmatch(path.name)
        if match is not None and path.is_dir():
            yield int(match.group(1)), path


def complete_space_ids(lean_root: Path = LEAN_ROOT) -> list[str]:
    """Discover implemented numbered modules, excluding scaffolds with proof debt."""
    modules = []
    for number, path in _numbered_directories(spaces_root(lean_root)):
        defs = path / "Defs.lean"
        lemmas = path / "Lemmas.lean"
        generated = path / "Generated.lean"
        if defs.is_file() and lemmas.is_file() and generated.is_file():
            source = "\n".join(
                file.read_text(encoding="utf-8")
                for file in (defs, lemmas, generated)
            )
            if not _PROOF_DEBT.search(source):
                modules.append((number, f"S{number}"))
    return [space_id for _, space_id in sorted(modules)]


def render_all(space_ids: Iterable[str]) -> str:
    normalized = sorted({normalize_space_id(value) for value in space_ids}, key=lambda x: int(x[1:]))
    imports = "".join(
        f"public import PiBaseLean.Spaces.{space_id}.Generated\n"
        for space_id in normalized
    )
    return f"module\n\n{ALL_HEADER}{ALL_AUDIT_IMPORT}{imports}"


def _write_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
    return True


def regenerate_all(lean_root: Path = LEAN_ROOT) -> tuple[Path, bool]:
    path = spaces_root(lean_root) / "All.lean"
    return path, _write_if_changed(path, render_all(complete_space_ids(lean_root)))


def _has_declaration(source: str, name: str) -> bool:
    return bool(
        re.search(
            rf"^[ \t]*(?:(?:public|noncomputable)[ \t]+)*def[ \t]+{re.escape(name)}\b",
            source,
            re.MULTILINE,
        )
    )


def _validate_numbered_imports(source: str, space_id: str, filename: str) -> list[str]:
    errors = []
    number = int(space_id[1:])
    required_suffix = {
        "Lemmas.lean": "Defs",
        "Generated.lean": "Lemmas",
    }.get(filename)
    found_required = required_suffix is None
    for imported_number, suffix in _IMPORT.findall(source):
        imported = int(imported_number)
        own_dependency = (
            required_suffix is not None
            and imported == number
            and suffix == required_suffix
        )
        if own_dependency:
            found_required = True
        else:
            errors.append(
                f"{space_id}/{filename}: numbered space import is not allowed: "
                f"PiBaseLean.Spaces.S{imported_number}"
                + (f".{suffix}" if suffix else "")
            )
    if not found_required:
        errors.append(
            f"{space_id}/{filename}: missing required numbered space import: "
            f"PiBaseLean.Spaces.{space_id}.{required_suffix}"
        )
    return errors


def validate_tree(
    lean_root: Path = LEAN_ROOT,
    *,
    check_all: bool = True,
    require_implemented: bool = True,
) -> list[str]:
    """Return deterministic convention violations without changing the tree."""
    root = spaces_root(lean_root)
    errors: list[str] = []
    if not root.exists():
        errors.append(f"missing spaces directory: {root}")
        return errors
    if not root.is_dir():
        return [f"spaces path is not a directory: {root}"]

    seen_numbers: dict[int, Path] = {}
    for path in sorted(root.iterdir(), key=lambda item: item.name):
        if path.name in {"All.lean", "Constructions"}:
            continue
        match = _SPACE_DIR.fullmatch(path.name)
        if match is None:
            if path.is_dir() or path.suffix == ".lean":
                errors.append(f"unexpected path in spaces directory: {path}")
            continue
        if not path.is_dir():
            errors.append(f"numbered space path is not a directory: {path}")
            continue
        number = int(match.group(1))
        canonical = f"S{number}"
        if number <= 0 or path.name != canonical:
            errors.append(f"non-canonical numbered space path: {path}; expected {canonical}")
        if number in seen_numbers:
            errors.append(
                f"duplicate normalized space paths: {seen_numbers[number]} and {path}"
            )
        else:
            seen_numbers[number] = path

        defs = path / "Defs.lean"
        lemmas = path / "Lemmas.lean"
        generated = path / "Generated.lean"
        required = (
            ("Defs.lean", defs),
            ("Lemmas.lean", lemmas),
            ("Generated.lean", generated),
        )
        if any(not file.is_file() for _, file in required):
            missing = [name for name, file in required if not file.is_file()]
            errors.append(
                f"{path.name}: incomplete module; missing {', '.join(missing)}"
            )
            continue

        defs_source = defs.read_text(encoding="utf-8")
        lemmas_source = lemmas.read_text(encoding="utf-8")
        generated_source = generated.read_text(encoding="utf-8")
        if not _has_declaration(defs_source, f"S{number}"):
            errors.append(f"{path.name}/Defs.lean: missing literal def S{number}")
        if require_implemented and _PROOF_DEBT.search(
            "\n".join((defs_source, lemmas_source, generated_source))
        ):
            errors.append(f"{path.name}: proof debt prevents implementation status")
        if not _has_declaration(defs_source, f"S{number}_canonicalHomeomorph"):
            errors.append(
                f"{path.name}/Defs.lean: missing def S{number}_canonicalHomeomorph"
            )
        errors.extend(_validate_numbered_imports(defs_source, canonical, "Defs.lean"))
        errors.extend(_validate_numbered_imports(lemmas_source, canonical, "Lemmas.lean"))
        errors.extend(
            _validate_numbered_imports(generated_source, canonical, "Generated.lean")
        )

    if check_all:
        all_path = root / "All.lean"
        expected = render_all(complete_space_ids(lean_root))
        if not all_path.is_file():
            errors.append(f"missing generated aggregate: {all_path}")
        elif all_path.read_text(encoding="utf-8") != expected:
            errors.append(f"stale generated aggregate: {all_path}")
    return errors


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("space_id", nargs="?", help="space ID, for example S147 or S000147")
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate conventions and generated files without writing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=LEAN_ROOT,
        help=argparse.SUPPRESS,
    )
    return parser


def run(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    lean_root = args.root.resolve()
    if not (lean_root / "PiBaseLean").is_dir():
        raise SpaceValidationError(f"not a PiBase Lean source root: {lean_root}")
    if args.check and args.space_id is not None:
        raise SpaceValidationError("--check does not accept a space ID")

    if args.check:
        errors = validate_tree(lean_root)
        if errors:
            raise SpaceValidationError("\n".join(errors))
        print(f"space modules are valid ({len(complete_space_ids(lean_root))} modules)")
        return 0

    if args.space_id is not None:
        defs, lemmas, generated, created = scaffold_space(args.space_id, lean_root)
        action = "created" if created else "kept existing"
        print(f"{action} {defs}, {lemmas}, and {generated}")

    errors = validate_tree(lean_root, check_all=False, require_implemented=False)
    if errors:
        raise SpaceValidationError("\n".join(errors))
    all_path, changed = regenerate_all(lean_root)
    print(f"{'wrote' if changed else 'unchanged'} {all_path}")
    return 0


def main() -> None:
    try:
        raise SystemExit(run())
    except SpaceValidationError as error:
        raise SystemExit(f"space generation error: {error}") from error


if __name__ == "__main__":
    main()
